# Generated by Django 4.0.1 on 2022-01-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта автора')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=200, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Гостевая книга',
                'verbose_name_plural': 'Гостевая книга',
                'db_table': 'Books',
            },
        ),
    ]
